default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: body_mass_index_challenge_development

test:
  <<: *default
  database: body_mass_index_challenge_test
