# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9f341ae67416f2638e0304c28d1879222baa1cdec71e065285e5e49ee50e0b0fcd7e1e2454b003a8ab64a093fc08486683dd3787f3c65df7ae25dfe03cdba630

test:
  secret_key_base: 4732317b8fcad18d2893bfe80681a7e2610f2ec352f8a461da3359e20a02554e2e7ef1edd530cde9ce276bda6bb69d42c90f91c208c5fc6bb036883d8c862bc4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
